<?php

namespace Lib\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * sanctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sanctionRepository extends EntityRepository
{
    public function listSanction()
    {
        $qb=  $this->createQueryBuilder('s');
        $qb= $qb->getQuery()->getArrayResult();
        return $qb;
    }
    public function read($id)
    {   $qb=  $this->createQueryBuilder('s');
        $qb=  $qb->select()->where($qb->expr()->eq('s.id', $id));
        $qb= $qb->getQuery()->getArrayResult();
        return $qb;
        
    }
}
